AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Globals:
  Function:
    Runtime: nodejs6.10
    MemorySize: 128
    Timeout: 15
  Api:
    EndpointConfiguration: REGIONAL
    Cors: "'www.example.com'"

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
# Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes

Resources:
  GOREST:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Environment:
        Variables:
          NODE_ENV: production
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        # API Gateway event to trigger this lambda function
        GetRoot:
          Type: Api
          Properties:
            Path: /
            Method: get
        # this will create another event triggering the same lambda function
        GetModels:
          Type: Api
          Properties:
            Path: /models
            Method: get
        # this will create yet another event triggering the same lambda function
        GetModel:
          Type: Api
          Properties:
            Path: /models/{id}
            Method: get
        # this will create yet another event triggering the same lambda function
        GetLastModels:
          Type: Api
          Properties:
            Path: /models/last/{nb}
            Method: get
